TrajectoryPlannerROS:
  max_vel_x: 0.2 #0.2
  min_vel_x: -0.2 #-0.2
  max_vel_theta: 0.3
  min_in_place_vel_theta: 0.7
  acc_lim_theta: 0.1
  acc_lim_x: 0.15  #0.05
  acc_lim_y: 0.1  # 0.2
  holonomic_robot: false
  yaw_goal_tolerance: 1.0 #2.0
  xy_goal_tolerance: 1.0 #0.3
  meter_scoring: true
  recovery_behavior_enabled: false
  clearing_rotation_allowed: false
  
  
